# Generated by Django 3.1.7 on 2021-03-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coins',
            field=models.PositiveIntegerField(default=0, verbose_name='Коины'),
        ),
        migrations.AlterField(
            model_name='question',
            name='primary_score',
            field=models.PositiveIntegerField(verbose_name='Первичный балл'),
        ),
        migrations.AlterField(
            model_name='testhistory',
            name='primary_source',
            field=models.PositiveIntegerField(default=0, verbose_name='Набранный балл'),
        ),
    ]
